# Generated by Django 2.2.6 on 2021-07-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210704_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, help_text='Укажите идентификатор URL', null=True, unique=True, verbose_name='Идентификатор URL'),
        ),
    ]
